"""empty message

Revision ID: 14a827a15270
Revises: 15eec8bea0cb
Create Date: 2022-06-17 13:43:40.180178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14a827a15270'
down_revision = '15eec8bea0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('answer', 'create_data')
    op.add_column('question', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('question', 'create_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('question', 'create_date')
    op.add_column('answer', sa.Column('create_data', sa.DATETIME(), nullable=False))
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
